#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI1 -d code db video
bspc monitor eDP1 -d www chat1 chat2 docs dsk dsk2 dsk3

bspc config border_width           2
bspc config window_gap             6
bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer false
bspc config normal_border_color   "#444"
bspc config focused_border_color  "#ffffff"

#bspc config external_rules_command $HOME/.config/bspwm/scripts/window_location

# Prevents emacs start floating
bspc rule -a Emacs state=tiled
# Yad calendar opens floating
bspc rule -a Yad state=floating follow=on

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

# Autorun applications
#

#nm-applet &
#xfce-power-manager &
xscreensaver -no-splash &
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &
picom &
polybar for_bspwm -r &
feh --bg-fill -z ~/Imagens/wallpapers/*.jpg &
$HOME/.local/bin/bspwm-cleanfullscreen &
xss-lock --transfer-sleep-lock -- i3lock-fancy &
dex --autostart --environment bspwm &
