#! /bin/sh

# Do not start sxhkd if already running
pgrep -x sxhkd > /dev/null || sxhkd &

# Multimonitor configuration
# default oly "RIGHT" monitor if only one connected
RIGHT_MONITOR=$MONITOR_2  # "eDP1"

QTD_MONITORS=$(xrandr | grep -sw 'connected' | wc -l)
if [ $QTD_MONITORS -gt "1" ]; then
    # Default left monitor to HDMI-1
    LEFT_MONITOR=$MONITOR_1
    # Try to load LEFT and RIGHT from custom local config if exists
    if [ -f $HOME/.config/bspwm/scripts/config ]; then
        eval $($HOME/.config/bspwm/scripts/config)
    fi
    # Arrange desktops between monitors
    bspc monitor $LEFT_MONITOR -d 1:code 2:term 3:www 4:db
    bspc monitor $RIGHT_MONITOR -d 5:chat1 6:chat2 7:docs 8:dsk 9:dsk1 10:dsk2
else
    # Only one monitor detected, so all desktops go in the same
    bspc monitor $RIGHT_MONITOR -d 1:code 2:term 3:www 4:db 5:chat1 6:chat2 7:docs 8:dsk 9:dsk1 10:dsk2
fi

# Default monitor for polybar is RIGHT
export POLYBAR_MONITOR=$RIGHT_MONITOR 

bspc config border_width           2
bspc config window_gap             6
bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer false
bspc config pointer_follows_focus false
bspc config pointer_follows_monitor false
bspc config normal_border_color   "#444"
bspc config focused_border_color  "#ffffff"

# external rules to cases not covered directly from bspc rule command
bspc config external_rules_command $HOME/.config/bspwm/scripts/window_location


# Prevents emacs start floating
bspc rule -a Emacs state=tiled

# Yad calendar opens floating
bspc rule -a Yad state=floating follow=on
bspc rule -a Gimp desktop='^8' follow=on
bspc rule -a DBeaver desktop="^4" #follow=on
bspc rule -a Slack desktop="^6" follow=on
bspc rule -a Deskreen desktop="^10" follow=on
bspc rule -a "VirtualBox Manager" desktop="^8" follow=on
bspc rule -a VirtualBoxVM desktop="^9" follow=on
bspc rule -a Thunar desktop="^7" follow=on
bspc rule -a Blueman-manager state=floating rectangle=500x300 center=true
bspc rule -a SpotPress state=floating center=true
bspc rule -a Chromium desktop='^3' follow=on
bspc rule -a Google-chrome desktop='^3' follow=on
bspc rule -a firefox desktop='^5' follow=on
bspc rule -a SshAskpass center true
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on bspc rule -a Screenkey manage=off

bspc rule -a ScratchPad sticky=on state=floating rectangle=1200x600+0+0 center=true
bspc rule -a PythonPad sticky=on state=floating rectangle=1200x600+0+0 center=true


# Autorun applications
#
setxkbmap -layout br 
# xscreensaver -no-splash &
# nm-applet &
# blueman-applet &

/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &
picom --experimental-backends &
$HOME/.local/bin/launch_polybar for_bspwm -r &
$HOME/.local/bin/cyclebg &
$HOME/.local/bin/setdesktopbg &
$HOME/.local/bin/bspwm-cleanfullscreen &
#flatpak run org.deskflow.deskflow &
deskflow &
#xset s 299
#xss-lock --transfer-sleep-lock -- i3lock-fancy -n &
#nm-applet &
#xfce-power-manager &
dex --autostart --environment bspwm &
bspc desktop -f ^1 --follow

