#!/bin/env bash
  
wid="$1"
#class="$2"
#instance="$3"
#eval "$4"
title="$(xprop -id $wid '\t$0' WM_NAME | cut -f 2)"
notify-send $title
if [[ "$title" = "WhatsApp Web"]]; then
    notify-send "$title"
    echo 'state=floating'
fi
